### ISSUE TITLE
BlackBuck47 Ban Request

### ISSUE THREAD

**Issue by Anthony-Webb** [PERPGamer/OHD-Communtiy-Ban-List#2]
**USER:**     `BlackBuck47`
**STEAMID:**     `76561198255102105`
**REASON:**     `Racial Slurs`
**SERVER:**    `[IT] New Horizons | Test`
**PHOTO:**     `https://imgur.com/6GQpkcy`

**NOTES:**     `I was unable to find the server or server owner in the O:HD Server_Listing discord channel.  `

**Comment by PERPGamer** [comment]
Added in https://github.com/PERPGamer/OHD-Communtiy-Ban-List/commit/8de246c32d16e8467f5b20ec4207dd7028e3ecb0

**Comment by Anthony-Webb** [comment]
> Added in [8de246c](https://github.com/PERPGamer/OHD-Communtiy-Ban-List/commit/8de246c32d16e8467f5b20ec4207dd7028e3ecb0)

Thanks!
