### ISSUE TITLE
Cheater

### ISSUE THREAD

**Issue by CPGAgain** [PERPGamer/OHD-Communtiy-Ban-List#3]
name:drogs
about: he's spamming explosive at an inhumane speed in powerbit's server, sending anti democratics messages and russian propaganda in the chat.
title:ac-130's cheaters
labels: Reported User
assignees:Couboo#1787

---

**Player's Steam64**:76561199219672973
https://steamid.io/lookup/76561199219672973

**Reason/Proof**:he's spamming explosive at an inhumane speed in powerbit's server, sending anti democratics messages and russian propaganda in the chat. yeah that's the only proof i'm able to get since i rarely use the 
screenshot feature

![Operation_ Harsh Doorstop   28_03_2023 17_57_11](https://user-images.githubusercontent.com/76166766/228227614-4237bad8-59f5-4f01-84fd-b07e915a628b.png)

**Comment by PERPGamer** [comment]
Added in [#8e7c6a6](https://github.com/PERPGamer/OHD-Communtiy-Ban-List/commit/8e7c6a62634d9de05bb4e936db8cf6fa4ce24ecf)
