### ISSUE TITLE
hacker /ddos

### ISSUE THREAD

**Issue by zabez** [PERPGamer/OHD-Communtiy-Ban-List#4]
76561199064229119:0
 
 https://steamid.io/lookup/76561199064229119
 
 cluster bomb hack 81 kills to 0, crashed the server

**Comment by PERPGamer** [comment]
Added in [8e7c6a6](https://github.com/PERPGamer/OHD-Communtiy-Ban-List/commit/8e7c6a62634d9de05bb4e936db8cf6fa4ce24ecf)
